apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-locations-consumer
  name: udaconnect-locations-consumer
spec:
  ports:
    - port: 9092
  selector:
    service: udaconnect-locations-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-locations-consumer
  name: udaconnect-locations-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-locations-consumer
  template:
    metadata:
      labels:
        service: udaconnect-locations-consumer
    spec:
      containers:
        - image: aabounegm/udaconnect-locations-consumer:latest
          name: udaconnect-locations-consumer
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: kafka-location-configmap
                  key: KAFKA_URL
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: kafka-location-configmap
                  key: KAFKA_TOPIC
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 125m
              memory: 128Mi
      restartPolicy: Always
