apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-locations-ingester
  name: udaconnect-locations-ingester
spec:
  ports:
    - port: 5005
  selector:
    service: udaconnect-locations-ingester
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-locations-ingester
  name: udaconnect-locations-ingester
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-locations-ingester
  template:
    metadata:
      labels:
        service: udaconnect-locations-ingester
    spec:
      containers:
        - name: udaconnect-locations-ingester
          image: aabounegm/udaconnect-locations-ingester:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: kafka-location-configmap
                  key: KAFKA_URL
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: kafka-location-configmap
                  key: KAFKA_TOPIC
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 125m
              memory: 128Mi
      restartPolicy: Always
