apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connections-api
  name: udaconnect-connections-api
spec:
  ports:
  - port: 5000
  selector:
    service: udaconnect-connections-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connections-api
  name: udaconnect-connections-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connections-api
  template:
    metadata:
      labels:
        service: udaconnect-connections-api
    spec:
      containers:
      - name: udaconnect-connections-api
        image: aabounegm/udaconnect-connections-api:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 125m
            memory: 128Mi
      restartPolicy: Always
