apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: udaconnect-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/locations
            pathType: Prefix
            backend:
              service:
                name: udaconnect-locations-api
                port:
                  number: 5000
          - path: /api/persons/.*/connection
            pathType: Prefix
            backend:
              service:
                name: udaconnect-connections-api
                port:
                  number: 5000
          - path: /api/persons
            pathType: Prefix
            backend:
              service:
                name: udaconnect-persons-api
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: udaconnect-app
                port:
                  number: 3000
